import { ProfileAvatar } from "@/components/ProfileAvatar";
import RelativeBreadCrumb from "@/components/RelativeBreadCrumb";
import SidebarComponent from "@/components/SidePanel";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen w-screen overflow-hidden">
            <div>
              <SidebarComponent />
            </div>
            <main className="box-border h-full w-full overflow-y-auto p-10">
              <div className="flex h-7 justify-between">
                <RelativeBreadCrumb />
                <ProfileAvatar />
              </div>
              <div className="h-[calc(100%-1.75rem)]">{children}</div>
            </main>
            <Toaster expand visibleToasts={1} />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
